
flujo=open('C:\\Users\\lozano\\OneDrive\\Documents\\ruben lozano\\SENA\\3er Trimestre\\Samuel Padilla\\Repositorio\\ADSO-B\\Comentarios\\Comentariosarchivos4\\Parte1\\basico.txt','r') #Se hace instanciacion de un objeto al que se le asigna como contenido la palabra reservada open la cual es una funcion de python que permite abrir archivos de texto para leer, escribir o agregar informacion, la funcion open () siempre pide dos parametros, el primero es basicamente para poner la ubicacion del archivo de texto dentro del computador donde puede ser ruta absoluta o ruta relativa, y el segundo parametro es lo que se quiere hacer con el archivo osea agregar, leer o escribir en el archivo y si el tipo es binario o texto.

#datos=flujo.read() #Se crea una variable local que contiene el nombre donde se instancio el archivo, pero con el metodo read() que permite leer lo que se encuentra en el archivo esto quiere decir que esto mostrara por consola lo que se encuentra en el archivo de texto.
#print(type(datos)) #Con este print y la funcion type que pide como parametro cualquier variable u objeto creado para mostrar por cconsola a que tipo de cllase pertenecen, en este caso se le pasa como parametro el objeto datos que contiene como el archivo en modo lectura, est quiere decir que mosttrara que es una clase tipo str
#flujo.write('Bienvenido al trabajo con archivos') #Aqui a flujo que es donde se abrio el archivo, se combina con el metodo writte que sirve para escribir y eliminar cualquier cosa que se encuentre en el archivo actual esto quiere decir que esto escribira 'Bienvenido al trabajo con archivos'
for dia in flujo: #Aqui se crea una estructura de control de iteracion basicamente un for que permitira recorrer el archivo de texto con una variable llamada dia que permitira recorrer el archivo para mostrar por consola su contenido.
    print(dia) #Con este print se imprimira todo el contennido del archivo de texto, osea todo su contenido linea por linea ya que la variable dia sirvio para recorrer el archivo y asi mostrarlo por consola aunque tambien se podria hacer con la funcion read().
#flujo.close() #El metodo close que es utilizado en este caso, sirve para cerrar por completo el archivo, este metodo es utilizado cuando no se utliza la palabra reservada with ya que este contiene un bloque de codigo para archivos osea si cierra el bloque de codigo pues se termina el procedimiento realizado con los archivos, entonces el metodo close () es utilizado si no se usa dicha palabra reservada.

with open ('C:\\Users\\lozano\\OneDrive\\Documents\\ruben lozano\\SENA\\3er Trimestre\\Samuel Padilla\\Repositorio\\ADSO-B\\Comentarios\\Comentariosarchivos4\\Parte1\\basico.txt','r') as flujo: #Se hace uso de la palabra reservada with que sirve para crear un bloque de codigo unico donde si se termina el proceso con los archivos no es necesario usar el metodo close(), despues de la palabra with siempre viene el metodo open() que sirve para abrit los archivos y contiene dos parametro, el primero donde se le pasa la ubicacion del archivo en el computador y el segundo parametro lo que se desea hacer con dicho archivo, ya sea leer, escribir, crearlo o agregar cosas al archivo sin eliminar lo existente, en este caso le pasamos la ubicacion del archivo la cual es '1eraParte/basico.txt' y en el segundo se le pasa la letra 'r' que sirve para leer el contenido del archivo, y despues de hacer uso de los 2 parametros de open(), se usa la palabra reservada as que es para darle un alias a lo antes escrito osea la abertura del archivo y este alias final que es flujo, y este nombre servira para trabajar con el archivo y finalmente se cierra con dos puntos.
    datos=flujo.read() # La variable datos guarda el archivo flujo osea basicamente el alias del archivo original con su metodo read() osea que cuando se haga impresion de la variable datos pues se mostrara por consola lo que contenga el archivo.
    print(datos) #Con el print pues se permite la impresion de la variable datos, que simplemente mostara todo el contenido del archivo.

with open ('1eraParte/basico.txt','r') as flujo: #Se hace uso de la palabra reservada with que sirve para crear un bloque de codigo unico donde si se termina el proceso con los archivos no es necesario usar el metodo close(), despues de la palabra with siempre viene el metodo open() que sirve para abrit los archivos y contiene dos parametro, el primero donde se le pasa la ubicacion del archivo en el computador y el segundo parametro lo que se desea hacer con dicho archivo, ya sea leer, escribir, crearlo o agregar cosas al archivo sin eliminar lo existente, en este caso le pasamos la ubicacion del archivo la cual es '1eraParte/basico.txt' y en el segundo se le pasa la letra 'r' que sirve para leer el contenido del archivo, y despues de hacer uso de los 2 parametros de open(), se usa la palabra reservada as que es para darle un alias a lo antes escrito osea la abertura del archivo y este alias final que es flujo, y este nombre servira para trabajar con el archivo y finalmente se cierra con dos puntos.
    for dia in flujo: #Con la palabra reservada for que da inicio a una iteracion, despues crea una variable local que sera dia y que recorrera el contenido del archivo en este caso flujo que es el alias del archivo total como se expresa en la linea de arriba.
        print(dia) #Este print imprimira la variable local que fue creada en la creacion del for y mostrara en pantalla simplemente el archivo flujo.