from Carga import * 
from Conductor import * #Se usa la palabra reservada from para indicar que archivo se va a importar en este caso es el archivo Conductor, despues se usa la palabra reservada import que se utiliza para saber que se va a importar de dicho archivo esto se refiere que se va a importar todo del archivo Conductor.
#c1=Conductor('Luis',12345) #Se instancia un objeto de la clase Conductor que sera c1, el cual como parametros osea nombre y documento tendra a 'luis' como primer parametro y '12345' como segundo parametro.
#carga1=Carga('aaa-123',c1,5,2) #Se instancia un nuevo objeto de la clase Carga que sera carga1, en este caso se le piden 4 parametros, como primer parametro placa, despues conductor como segundo parametro, como tercer parametro capacidad en toneladas y como cuarto y ultimo se le psa el numero de ejes de la maquina.
#print(carga1) #Aqui se imprime por consola el objeto carga1 que sera o se mostrar por consola la direccion en memoria del mismo, esto quiere decir que no se muestra el contenido solo su ubicacion.
nomConductor=input('Ingrese nombre del conductor') #Se crea una variable local llamada nomConductor que sera un input que pedira una cadena de texto que tendra como mensaje 'Ingrese nombre del conductor'.
docConductor=int(input('Ingrese documento del conductor')) #Se crea una variable local llamada docConductor que sera un input que pedira un numero entero que tendra como mensaje 'Ingrese documento del conductor'.
placa=input('ingrese placa') #Se crea una variable local llamada placa que sera un input que pedira una cadena de texto que tendra como mensaje 'Ingrese placa'.
capacidad=input('ingrese capacidad en toneladas') #Se crea una variable local llamada capacidad que sera un input que pedira una cadena de texto que tendra como mensaje 'Ingrese capcidad en toneladas'.
ejes=input('ingrese numero de ejes')#Se crea una variable local llamada ejes que sera un input que pedira una cadena de texto que tendra como mensaje 'Ingrese numero de ejes'.
c1=Conductor(nomConductor,docConductor) #Se instancia un nuevo objeto de la clase Conductor, su nombre es 'c1' y pide dos parametros el nombre y el documento del conductor, se le pasa como primer parametro la variable nommConductor que sera pedida para ser ingresada por teclada, y como segundo parametro sera docConductor que tambien sera pedido para ser ingresado por teclado.
obCarga=Carga(placa,c1,capacidad,ejes) #Se instancia un nuevo objeto de la clase Carga, su nombre es 'obCarga' y piide 4 parametros, primero sera la variable placa que sera pedida por teclado, despues se le pasara el objeto c1 que contiene la informacion del conductor, despues como tercer parametro capacidad que sera ingresada por teclado y como cuarto y ultimo parametro se le pasara la variable ejes que tambien sera ingresada por teclado.
cadConductor=obCarga.getConductor().getNombre()+','+str(obCarga.getConductor().getDocumento()) #Se crea una variable local que es cadConductor, esta contiene el objeto obCargacon el metodo getConductor().getNombre() que sirve para vizualizar en pantalla el nombre del conductor ingresado, despues se concatena con la siguiente cadena de texto, pero antes todo el contenido ira dentro de la funcion str que sirve para convertir numeros a strings, en esta se llama el objeto obCarga con el metodo getConductor().con el metodo getDocumento() que mostrara por pantalla el codumento del conductor, finalmente tod se convertira a cadena de texto y sera el nombre y el documento.
cadCarga=obCarga.getPlaca()+','+cadConductor+','+str(obCarga.getCapacidad())+','+str(obCarga.getEjes()) #Se crea una variable local que sera cadCarga, esta primero contendra el objeto obCarga con el metodo getPlaca() que mostrara por pantalla la palca del vehiculo, despues este metodo se concatenara con la anterior variable creada osea cadConductor y esta variable se concatenara obCarga.getCapacodad() que mostrara por pantalla la capacidad del vehiculo en toneladas obviamente todo esto ira dentro de la funcion str que convertira el numero a string, y por ultimo ira el objeto obCarga con el metodo getEjes() que mostrara por pantalla los ejes del vehiculo, pero ira dentro de la funcion str que convertira el numero de ejes a string.
with open('C:\\Users\\lozano\\OneDrive\\Documents\\ruben lozano\\SENA\\3er Trimestre\\Samuel Padilla\\Repositorio\\ADSO-B\\Comentarios\\Comentariosarchivos4\\Parte2\\basico.txt','a') as flujo: #Aqui se hace uso de la palabra reservada with que sera la que ayude a manipular el archivo con su bloque de codigo, despues de with viene la palabra tambien reservada open() que se usa para abrir un archivo en su lista de parametros tiene la ruta del archivo que ya fue indica de forma absoluta y de segundo parametro contiene lo que se desea hacer con el archivo ya sea agregar, crear el archivo, escribir en el archivo o leer el archivo, como en este caso esta la a entonces se agregara al archivo en una nueva linea, despues de esto viene as que es para poner un alias al archivo y su alias en este caso sera flujo.
    flujo.write(cadCarga+'\n') #Se hace llamado del archivo o su alias que es flujo, con el metodo write. que sirve para escribir nuevas cosas dentro del archivo, se le pasara la cadena final osea toda la informacion que fue antes ingresada por teclado y un salto de linea.