import csv #Se usa la palabra reservada imposrt que sirve para importar un modulo propio de python o un modulo creado por el programador, y se importa el modulo csv que trae incorporado todas las funcionalidades que sirve para manipulas archivos csv.
header=['Fruit','Price'] #Se crea una variable local que se llama header y que contiene una lista con dos valores, el primero es fruit y el segundo es price.
rows=[['Apple',1200], #Se crea una variable nueva que contiene listas dentro listas, la variable es llamda rows que basicamente se traduciria como filas, el primer valor de la primera fila es 'Apple' y el segundo valor de la fila es '1200'.
      ['Berry',2000], #El primer valor de la segunda fila es 'Berry' y el segundo valor de la fila es '2000'.
      ['Lemon',1000], #El primer valor de la tercera fila es 'Lemon' y el segundo valor de la fila es '1000'.
      ['Melon',3000], #El primer valor de la cuarta fila es 'Melon' y el segundo valor de la fila es '3000'.
      ['Grapes',4000], #El primer valor de la quinta fila es 'Grapes' y el segundo valor de la fila es '4000'.
      ['Pear',2000]] #El primer valor de la sexta fila es 'Pear' y el segundo valor de la fila es '2000'.

with open ('4ta Parte/example.csv','w') as csvfile: #Se usa la palabra reservada with para crear un bloque de codigo para la manipulacion del archivo csv, despues de la palabra reservada with se usa la palabra open() o metodo de archivos que sirve para abrir un archivo el cual pide dos parametros o tres en los diferentes casos, el primer parametro es para poner la ruta del archivo que se desea manipular, el segundo parametro es en que modo se desea usar el archivo si es modo leer, agregar, escribir o crear, en este caso se pone la direccion del archivo y despues se pone la letra 'w' que basicamente sirve para eliminar y escribir en el archivo, despues de los parametros viene la palabra reservada as que sirve para poner un alias al archivo y basicamente manipularlo, despues se le asigna dicho alias que en este caso 'csvfile'.
    csvwriter=csv.writer(csvfile) #Se crea una variable local que es csvwriter que servira para escribir dentro del archivo csv, el contenido de dicha variable es un metodo del modulo importado csv es cual es writer que pide un parametro en este caso se le pasa como parametro para que escriba en dicho archivo el archivo 'csvfile'.
    csvwriter.writerow(header) #Despues de asignar lo anterior a la variable local 'csvwriter' se usa un nuevo metodo del modulo csv el cual es writerow que sirve para escribir una fila dentro del archivo csv y pide un parametro, en este caso se le pasa la variable header que contiene el valor fruit y price, esta hara el trabajo de la cabecera para indicar que se encontrara dentro del archivo csv.
    csvwriter.writerows(rows) #Se usa un nuevo metodo del modulo csv con la variable csvwriter que es writerows que se usa para escribir varias filas dentro del archivo csv, en este caso se le pasa un parametro osea la variable rows que contiene listas dentro de una lista, esto se refiere a que los datos de rows vasn a ser escritos en el archivo csv.